

function [AllLabelPaths,AllT1Bet] = Atlas2SubjectSpace(FAPathCell,T1PathCell,Options)

%% Options PANDA program:
BrainParcellation_opt.T1Bet_Flag= 1;
BrainParcellation_opt.T1BetF= 0.4000;
BrainParcellation_opt.T1Cropping_Flag= 1;
BrainParcellation_opt.T1CroppingGap= 3;
BrainParcellation_opt.T1Resample_Flag= 1;
BrainParcellation_opt.T1ResampleResolution= [1 1 1];
BrainParcellation_opt.PartitionTemplatePath= [ pwd '/lib/PANDA_1.3.1_64/data/atlases/AAL/AAL_Contract_90_2MM'];
BrainParcellation_opt.T1TemplatePath= [ pwd '/lib/PANDA_1.3.1_64/data/Templates/MNI152_T1_2mm_brain'];

BrainParcellationPipeline_opt.flag_verbose= 1;
BrainParcellationPipeline_opt.flag_pause= 0;
BrainParcellationPipeline_opt.mode= 'background';
BrainParcellationPipeline_opt.max_queued= 4;
BrainParcellationPipeline_opt.path_logs= [pwd '/lib/PANDA_1.3.1_64/BrainParcellation_logs'];

for u = 1:length(FAPathCell)
    
    %% Extract Info
    
    [~,atlas_name,~] = fileparts(BrainParcellation_opt.PartitionTemplatePath);
    [parcelated_folder,~,~] = fileparts(FAPathCell{u});
    [eddy_folder,~,~] = fileparts(parcelated_folder);
    parcelated_file_path = [parcelated_folder '/dti_FA_Parcellated_' atlas_name '.' Options.ConvertFormat];
    New_parcelated_file_path = [eddy_folder '/Labels_' atlas_name '.' Options.ConvertFormat];
    
    
    if ~exist(New_parcelated_file_path,'file')
        
        FA{1} = FAPathCell{u};
        T1{1} = [T1PathCell{u}];
        
        %% Label to DWI
        try
            g_BrainParcellation_pipeline(FA, T1, BrainParcellation_opt, BrainParcellationPipeline_opt)
        catch erro
        end
        
        %% Organize generated files:
        
        % Write Path
        AllLabelPaths{u} = New_parcelated_file_path;
        % Move Files
        movefile(parcelated_file_path,New_parcelated_file_path)
        % Force atlas to have consecutive labels
        Relabel_atlas(New_parcelated_file_path);
        
        % Move T1 file:
        [t1Folder,~,~] = fileparts(T1PathCell{u});
        tempT1path = [eddy_folder '/T1/anat_swap_bet_crop_resample_2FA.' Options.ConvertFormat];
        newT1path = [t1Folder '/bet_anat2dwi.' Options.ConvertFormat];
        
        AllT1Bet{u} = newT1path;
        
        %Remove extra files generated by PANDA
        rmdir([eddy_folder '/T1'],'s')
        rmdir([eddy_folder '/quality_control'],'s')
        
        
    end
    
end